export const doctorList = [
  {
    id: 1,
    name: "Dr. Ayesha Khan",
    specialty: "Cardiologist",
    description: "Cardiovascular expert with over 10 years of experience in treating heart diseases.",
    likes: 245,
    rating: 4.8,
    consultationFee: 300,
    languages: ["English", "Arabic", "Hindi"],
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    available: true,
    location: "Medcare Hospital, Dubai",
  },
  {
    id: 2,
    name: "Dr. Omar Al-Farsi",
    specialty: "Dermatologist",
    description: "Skincare specialist focusing on acne, pigmentation, and anti-aging treatments.",
    likes: 188,
    rating: 4.3,
    consultationFee: 250,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/men/55.jpg",
    available: false,
    location: "SkinPlus Clinic, Abu Dhabi",
  },
  {
    id: 3,
    name: "Dr. Sara Nadeem",
    specialty: "Pediatrician",
    description: "Child health expert with a passion for preventive care and vaccination programs.",
    likes: 320,
    rating: 4.7,
    consultationFee: 200,
    languages: ["English", "Urdu"],
    image: "https://randomuser.me/api/portraits/women/68.jpg",
    available: true,
    location: "Healthy Kids Hospital, Sharjah",
  },
  {
    id: 4,
    name: "Dr. Faisal Qureshi",
    specialty: "Neurologist",
    description: "Specialist in treating migraines, epilepsy, and neurodegenerative disorders.",
    likes: 410,
    rating: 4.9,
    consultationFee: 350,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/men/61.jpg",
    available: true,
    location: "NeuroCare Center, Dubai",
  },
  {
    id: 5,
    name: "Dr. Lina Haddad",
    specialty: "Psychiatrist",
    description: "Focused on youth mental health, therapy, and medication management.",
    likes: 278,
    rating: 4.5,
    consultationFee: 280,
    languages: ["English", "Arabic", "French"],
    image: "https://randomuser.me/api/portraits/women/50.jpg",
    available: false,
    location: "MindWell Clinic, Ajman",
  },
  {
    id: 6,
    name: "Dr. Hamid Raza",
    specialty: "Orthopedic Surgeon",
    description: "Experienced in joint replacement, sports injuries, and trauma cases.",
    likes: 350,
    rating: 4.6,
    consultationFee: 400,
    languages: ["English", "Urdu"],
    image: "https://randomuser.me/api/portraits/men/34.jpg",
    available: true,
    location: "OrthoPlus Center, Dubai",
  },
  {
    id: 7,
    name: "Dr. Noura El-Sayed",
    specialty: "Gynecologist",
    description: "Women's health advocate with focus on reproductive health and prenatal care.",
    likes: 270,
    rating: 4.4,
    consultationFee: 320,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/women/29.jpg",
    available: true,
    location: "City Women's Clinic, Abu Dhabi",
  },
  {
    id: 8,
    name: "Dr. Bilal Hashmi",
    specialty: "Oncologist",
    description: "Cancer care specialist with a focus on chemotherapy and holistic treatment approaches.",
    likes: 390,
    rating: 4.7,
    consultationFee: 450,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/men/70.jpg",
    available: false,
    location: "Emirates Cancer Center, Dubai",
  },
  {
    id: 9,
    name: "Dr. Zainab Mustafa",
    specialty: "ENT Specialist",
    description: "Expert in treating ear, nose, and throat conditions with minimally invasive techniques.",
    likes: 190,
    rating: 4.2,
    consultationFee: 270,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/women/37.jpg",
    available: true,
    location: "Sinus & Ear Clinic, Sharjah",
  },
  {
    id: 10,
    name: "Dr. Tariq Hossain",
    specialty: "Endocrinologist",
    description: "Diabetes, thyroid, and hormone disorder specialist with over 15 years of experience.",
    likes: 420,
    rating: 4.8,
    consultationFee: 350,
    languages: ["English", "Bengali"],
    image: "https://randomuser.me/api/portraits/men/28.jpg",
    available: true,
    location: "Hormone Health Center, Dubai",
  },
  {
    id: 11,
    name: "Dr. Amal Al-Mansoori",
    specialty: "Family Medicine",
    description: "Trusted general practitioner providing holistic care for families and individuals.",
    likes: 305,
    rating: 4.3,
    consultationFee: 200,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/women/80.jpg",
    available: true,
    location: "Al Noor Family Clinic, Ajman",
  },
  {
    id: 12,
    name: "Dr. Jamal Akhtar",
    specialty: "Pulmonologist",
    description: "Respiratory specialist for asthma, COPD, and sleep apnea treatments.",
    likes: 265,
    rating: 4.4,
    consultationFee: 320,
    languages: ["English", "Urdu"],
    image: "https://randomuser.me/api/portraits/men/75.jpg",
    available: false,
    location: "BreathWell Center, Dubai",
  },
  {
    id: 13,
    name: "Dr. Maha Shakir",
    specialty: "Nutritionist",
    description: "Certified dietitian helping patients with weight loss, diabetes, and healthy lifestyle changes.",
    likes: 150,
    rating: 4.1,
    consultationFee: 180,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/women/12.jpg",
    available: true,
    location: "FitLife Nutrition, Abu Dhabi",
  },
  {
    id: 14,
    name: "Dr. Sameer Bhatti",
    specialty: "Urologist",
    description: "Urological surgeon experienced in kidney stones, prostate issues, and male health.",
    likes: 233,
    rating: 4.5,
    consultationFee: 300,
    languages: ["English", "Urdu"],
    image: "https://randomuser.me/api/portraits/men/40.jpg",
    available: false,
    location: "UroCare Clinic, Sharjah",
  },
  {
    id: 15,
    name: "Dr. Hiba Rehman",
    specialty: "Ophthalmologist",
    description: "Eye care specialist offering treatments for vision correction and glaucoma.",
    likes: 310,
    rating: 4.6,
    consultationFee: 280,
    languages: ["English", "Arabic"],
    image: "https://randomuser.me/api/portraits/women/21.jpg",
    available: true,
    location: "ClearVision Eye Center, Dubai",
  },
];
